USE [master]
GO

/****** Object:  Database [CourseRegistration]    Script Date: 1/23/2017 1:06:05 AM ******/
CREATE DATABASE [CourseRegistration]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CourseRegistration', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\CourseRegistration.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CourseRegistration_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\CourseRegistration_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [CourseRegistration] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CourseRegistration].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CourseRegistration] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CourseRegistration] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CourseRegistration] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CourseRegistration] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CourseRegistration] SET ARITHABORT OFF 
GO

ALTER DATABASE [CourseRegistration] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CourseRegistration] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CourseRegistration] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CourseRegistration] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CourseRegistration] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CourseRegistration] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CourseRegistration] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CourseRegistration] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CourseRegistration] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CourseRegistration] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CourseRegistration] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CourseRegistration] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CourseRegistration] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CourseRegistration] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CourseRegistration] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CourseRegistration] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CourseRegistration] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CourseRegistration] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CourseRegistration] SET  MULTI_USER 
GO

ALTER DATABASE [CourseRegistration] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CourseRegistration] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CourseRegistration] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CourseRegistration] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CourseRegistration] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CourseRegistration] SET QUERY_STORE = OFF
GO

USE [CourseRegistration]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [CourseRegistration] SET  READ_WRITE 
GO


